name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.71.0
  geolocator: ^14.0.2
  go_router: ^17.1.0
  google_maps_flutter: ^2.14.2
  http: ^1.2.0
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  pdf: ^3.11.3
  printing: ^5.14.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
